service: reporting
api_version: 1
threadsafe: true
runtime: custom
env: flex

runtime_config:
    python_version: 3.6

entrypoint: gunicorn -b :$PORT main:app

liveness_check:
  path: '/keep-alive'
  check_interval_sec: 300
  timeout_sec: 299
  failure_threshold: 10
  success_threshold: 1
  initial_delay_sec: 1000


manual_scaling:
  instances: 1

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
# [END handlers]


